services:
  app:
    image: 'python:3.12-alpine'
    build:
      context: 'https://github.com/miuguelt/fincaVillaLuz-main.git#main'
      dockerfile: Dockerfile
    ports:
      - '3000:8081'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_COOKIE_DOMAIN=${JWT_COOKIE_DOMAIN}
      - FLASK_ENV=${FLASK_ENV}
      - USE_HTTPS=${USE_HTTPS}
      - SSL_CERT_FILE=${SSL_CERT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
      - PORT=${PORT}
      - API_BASE_URL=${API_BASE_URL}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_PROTOCOL=${API_PROTOCOL}
      - FRONTEND_URL=${FRONTEND_URL}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL}
      - BACKEND_URL=${BACKEND_URL}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_PROTOCOL=${BACKEND_PROTOCOL}
    env_file:
      - .env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge